# Generated by Django 3.0.7 on 2020-06-18 19:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Page name')),
                ('heading', models.CharField(max_length=120, verbose_name='Page heading')),
            ],
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', max_length=30, verbose_name='Campaign code')),
                ('micetype', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Property name')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PaywallOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Offer name')),
                ('offerID', models.CharField(max_length=10, verbose_name='Offer ID')),
                ('monthlyStrikePrice', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Monthly strike price')),
                ('monthlyPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monthly price')),
                ('monthlyTermID', models.CharField(max_length=10, verbose_name='Monthly term ID')),
                ('annualStrikePrice', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Monthly strike price')),
                ('annualPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Annual price')),
                ('annualTermID', models.CharField(max_length=10, verbose_name='Annual term ID')),
                ('landingPage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.LandingPage')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Offer group name')),
                ('deliveryType', models.CharField(choices=[('DA', 'Daily'), ('WK', 'Weekend')], default='DA', max_length=2, verbose_name='Type')),
                ('monthlyName', models.CharField(max_length=120, verbose_name='Monthly offer name')),
                ('monthlyStrikePrice', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Monthly strike price')),
                ('monthlyPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monthly price')),
                ('monthlyTerm', models.CharField(choices=[('FW', '4 week'), ('MO', 'Month')], default='MO', max_length=2, verbose_name='Monthly term')),
                ('annualName', models.CharField(max_length=120, verbose_name='Annual offer name')),
                ('annualStrikePrice', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, verbose_name='Annual strike price')),
                ('annualPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Annual price')),
                ('landingPage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.LandingPage')),
            ],
        ),
        migrations.AddField(
            model_name='landingpage',
            name='pageType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.PageType'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Property'),
        ),
    ]
