# Generated by Django 3.0.7 on 2020-06-18 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetype',
            name='micetype',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='micetype',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Mice type'),
        ),
    ]
